### ISSUE TITLE
Integration to d3-force?

### ISSUE THREAD

**Issue by guy-kdm** [twosixlabs/d3-force-reuse#2]
Hi, just wondering if there is / was a reason why this wasn't contributed to the official repo?

**Comment by rpgove** [comment]
I felt that having a separate repo was the fastest way to make this available to the public. I have not asked Mike Bostock about this, so I don't know how he feels integrating it in d3-force. If this plugin becomes popular, I think it would be worth discussing integrating this into the d3-force repo.
