### ISSUE TITLE
How to set the initial layout use d3-force-reuse

### ISSUE THREAD

**Issue by Edward-Elric233** [twosixlabs/d3-force-reuse#3]
D3-Force works fine when I set the initial layout to d3-force, but I get errors when I set the initial layout to d3-force-reuse.
Am I setting it the wrong way or does D3-Force-Reuse not support setting the initial layout?
I set the initial layout by adding an x, y attribute to the nodes data.
Thanks for help
![image](https://user-images.githubusercontent.com/45136205/120623018-ea970580-c491-11eb-89e7-afdb7fa60458.png)

**Comment by rpgove** [comment]
I can't think of any reason it shouldn't work. Can you share example code?

**Comment by Edward-Elric233** [comment]
> I can't think of any reason it shouldn't work. Can you share example code?

I put my code in this URL:https://paste.ubuntu.com/p/4Rx5Z3pVy6/
It requires d3-force-reuse.js.
Thank you very much for your help.

**Comment by rpgove** [comment]
That works fine for me. I don't see any errors in the console. This is what I see:

![image](https://user-images.githubusercontent.com/2725258/120677714-6038ac80-c465-11eb-875b-3f0b1c042f30.png)

Is there any other information you can provide?

**Comment by Edward-Elric233** [comment]
> That works fine for me. I don't see any errors in the console. This is what I see:
> 
> ![image](https://user-images.githubusercontent.com/2725258/120677714-6038ac80-c465-11eb-875b-3f0b1c042f30.png)
> 
> Is there any other information you can provide?

Sorry, I found that I used the wrong version of d3-force-reuse.js. After redownloading it, it will also work here. Thank you for your help
