### ISSUE TITLE
Does it work in d3.js V5?

### ISSUE THREAD

**Issue by xuyaqist** [twosixlabs/d3-force-reuse#4]
When I change the d3.js version into v5, suddenly it didn't work, and there's no error in the console. What can I do to make it work in d3.js v5?

**Comment by rpgove** [comment]
It's worked for me on several D3 versions (4+). Do you have an example you can share?

**Comment by xuyaqist** [comment]
I've found the reason, it's because in v5, the` d3.json("miserables.json", function(){ });` has changed into `d3.json("").then(function() { });`, when I changed this, the code worked.

**Comment by xuyaqist** [comment]
Besides, I have another question. When I run the example  [d3-force-reuse speed comparison](https://bl.ocks.org/rpgove/ecee35052e3e81126dcefff134c06dae) in my computer locally, I cannot get a similar result. The time is always longer than the expectation. I am wondering, are there any other factors that can influence the time result?

**Comment by rpgove** [comment]
In retrospect, I should have measured the total time to compute the layouts, rather than the time for each tick. Measuring the time for each tick on such a small graph results in wild variation in time between runs, and especially between machines.

**Comment by Nantris** [comment]
@xuyaqist @rpgove is the conclusion that `d3-force-reuse` still provides performance gains over the default configuration? Or does D3 V5 (and V6/V7) make it irrelevant, or even harmful for performance?
